### ISSUE TITLE
dev zero, not dev null

### ISSUE THREAD

**Issue by squigley** [bsodmike/s5clouds8-lsi9211-8i-IR-to-IT-EFI-bootable-usb#1]
You gave me a head scratcher why dd wouldn't work..

```
sudo dd if=/dev/null of=/dev/sdf bs=16k status=progress
0+0 records in
0+0 records out
```
Then I realised it's because /dev/null is empty, so you can't copy it, or you get nothing, as opposed to using /dev/zero, which will give you all zeros and blank the drive.

**Comment by bsodmike** [comment]
Wow, thanks @squigley for that massive typo!

**Comment by bsodmike** [comment]
@squigley were you able to get your HBA card working?

**Comment by squigley** [comment]
No, I have a few similar cards, and they all refuse to flash properly. I can blank them, hostboot them, flash them, but then they don't come up properly, or they refuse to flash with the Mfg Page 2 error, and even sas2hax has the same issue.
